In [72]:
import pandas as pd
import numpy as np
import sys
import os
sys.path.append(os.path.abspath(".."))
from core.viz import plot_bar, plot_dynamic_trends, plot_line, plot_corr_triangle, plot_scatter, plot_statistical_strip, plot_heatmap
from core.s3 import S3AssetManager

In [2]:
notebook_name = "fortidex_harina_camaron"
s3 = S3AssetManager(notebook_name=notebook_name)

In [19]:
control = pd.read_excel(
    "../raw/fortidex/HUMEDADES EN LINEA PRO CAMARÓN 2025.xlsb",
     sheet_name="CLEAR",
     #skiprows=8,
     engine="pyxlsb")

In [20]:
control['FECHA'] = pd.to_numeric(control['FECHA'], errors='coerce')
#control['FECHA'] = pd.to_datetime(control['FECHA'], unit='D')
control['HORA'] = pd.to_timedelta(control['HORA'], unit='D', errors='coerce')
control = control[control["FECHA"].notna()]

In [21]:
control

,FECHA,HORA,TURNO,LOTE,PALLET,PT_25,PT_50,REPROCESO_25,REPROCESO_50,OBSERVACIÓN,...,PPM,FLUJO,VARIADOR,NOMBRE,SIPERNAT_SI,SIPERNAT_NO,INIMHOL_INICIO_KG,INIMHOL_FIN_KG,INIMHOL_TOTAL_KG,INIMHOL_DOSIS_KG/TON
0,45674.0,0 days 02:55:00.000000001,1.0,4135-01-2025,NaN,NaN,NaN,46.0,NaN,LIMPIEZA DEL SISTEMA,...,530.434783,22.0,60.0,GREENOX,NaN,ü,118.00,116.15,1.85,1.608696
1,45674.0,0 days 04:00:00.000000002,1.0,4135-01-2025,1--2,140.0,NaN,NaN,NaN,NaN,...,1811.428571,19.0,40.0,GREENOX,NaN,ü,116.15,111.60,4.55,1.3
2,45674.0,0 days 06:20:00,1.0,4135-01-2025,3--4 + 50 SACOS,190.0,NaN,NaN,NaN,NaN,...,1705.263158,19.0,40.0,GREENOX,NaN,ü,205.85,203.75,2.10,2.0
3,45675.0,0 days 01:20:00.000000003,1.0,4135-01-2025,NaN,NaN,NaN,42.0,NaN,LIMPIEZA DEL SISTEMA,...,390.47619,22.0,60.0,GREENOX,NaN,ü,203.75,201.80,1.95,1.695652
4,45675.0,0 days 01:45:00.000000002,1.0,4135-01-2025,NaN,NaN,NaN,46.0,NaN,HARINA SECA,...,1895.652174,25.0,45.0,GREENOX,NaN,ü,201.80,195.35,6.45,1.228571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,45927.0,0 days 20:10:00.000000001,2.0,07-270-2025,6--7--8 + 44 SACOS,NaN,NaN,254.0,NaN,NaN,...,840.944882,21.0,45.0,GREENOX,NaN,ü,NaN,NaN,0.00,0x7
866,45928.0,0 days 20:50:00.000000003,1.0,71-271-2025,NaN,NaN,NaN,NaN,19.0,LIMPIEZA SISTEMA (PESCADO),...,357.894737,20.0,60.0,GREENOX,NaN,ü,NaN,NaN,0.00,0x7
867,45928.0,0 days 21:00:00,1.0,72-271-2025,NaN,NaN,NaN,NaN,17.0,LIMPIEZA SISTEMA (CAMARÓN),...,282.352941,20.0,60.0,GREENOX,NaN,ü,NaN,NaN,0.00,0x7
868,45928.0,0 days 22:30:00,1.0,07-271-2025,1--2,NaN,NaN,140.0,NaN,NaN,...,831.428571,22.0,45.0,GREENOX,NaN,ü,NaN,NaN,0.00,0x7
869,45928.0,0 days 00:09:59.999999996,1.0,07-271-2025,3--4--5--6++42 sacos,NaN,NaN,322.0,NaN,NaN,...,891.925466,22.0,45.0,GREENOX,NaN,ü,NaN,NaN,0.00,0x7

In [22]:
control.columns

Index(['FECHA', 'HORA', 'TURNO', 'LOTE', 'PALLET', 'PT_25', 'PT_50',
       'REPROCESO_25', 'REPROCESO_50', 'OBSERVACIÓN', 'HUM', 'PROTEINA',
       'GRASA', 'CENIZA', 'GRANULOMETRIA', 'TEMP', 'TEMP_POND', 'TVN',
       'CONCENTRADO', 'COLOR', 'DOSIS', 'PT_SACOS', 'PT_TON',
       'ANTIOXIDANTE_INICIO_KG', 'ANTIOXIDANTE_FIN_KG',
       'ANTIOXIDANTE_TOTAL_KG', 'DOSIS_KG_TON', 'PPM', 'FLUJO', 'VARIADOR',
       'NOMBRE', 'SIPERNAT_SI', 'SIPERNAT_NO', 'INIMHOL_INICIO_KG',
       'INIMHOL_FIN_KG', 'INIMHOL_TOTAL_KG', 'INIMHOL_DOSIS_KG/TON'],
      dtype='object')

In [23]:
cols_num = [
'PT_25', 'PT_50',
'REPROCESO_25', 'REPROCESO_50',
'HUM', 'PROTEINA',
'GRASA', 'CENIZA', 'GRANULOMETRIA',
'TEMP', 'TEMP_POND', 
'COLOR', 'DOSIS', 'PT_SACOS', 'PT_TON',
'ANTIOXIDANTE_INICIO_KG', 
'ANTIOXIDANTE_FIN_KG',
'ANTIOXIDANTE_TOTAL_KG',
'DOSIS_KG_TON', 'PPM', 'FLUJO', 'VARIADOR',
'INIMHOL_INICIO_KG',
'INIMHOL_FIN_KG',
'INIMHOL_TOTAL_KG',
'INIMHOL_DOSIS_KG/TON'
]

In [24]:
for cl_num in cols_num:
    control[cl_num] = pd.to_numeric(control[cl_num], errors="coerce")

In [25]:
control

,FECHA,HORA,TURNO,LOTE,PALLET,PT_25,PT_50,REPROCESO_25,REPROCESO_50,OBSERVACIÓN,...,PPM,FLUJO,VARIADOR,NOMBRE,SIPERNAT_SI,SIPERNAT_NO,INIMHOL_INICIO_KG,INIMHOL_FIN_KG,INIMHOL_TOTAL_KG,INIMHOL_DOSIS_KG/TON
0,45674.0,0 days 02:55:00.000000001,1.0,4135-01-2025,NaN,NaN,NaN,46.0,NaN,LIMPIEZA DEL SISTEMA,...,530.434783,22.0,60.0,GREENOX,NaN,ü,118.00,116.15,1.85,1.608696
1,45674.0,0 days 04:00:00.000000002,1.0,4135-01-2025,1--2,140.0,NaN,NaN,NaN,NaN,...,1811.428571,19.0,40.0,GREENOX,NaN,ü,116.15,111.60,4.55,1.300000
2,45674.0,0 days 06:20:00,1.0,4135-01-2025,3--4 + 50 SACOS,190.0,NaN,NaN,NaN,NaN,...,1705.263158,19.0,40.0,GREENOX,NaN,ü,205.85,203.75,2.10,2.000000
3,45675.0,0 days 01:20:00.000000003,1.0,4135-01-2025,NaN,NaN,NaN,42.0,NaN,LIMPIEZA DEL SISTEMA,...,390.476190,22.0,60.0,GREENOX,NaN,ü,203.75,201.80,1.95,1.695652
4,45675.0,0 days 01:45:00.000000002,1.0,4135-01-2025,NaN,NaN,NaN,46.0,NaN,HARINA SECA,...,1895.652174,25.0,45.0,GREENOX,NaN,ü,201.80,195.35,6.45,1.228571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,45927.0,0 days 20:10:00.000000001,2.0,07-270-2025,6--7--8 + 44 SACOS,NaN,NaN,254.0,NaN,NaN,...,840.944882,21.0,45.0,GREENOX,NaN,ü,NaN,NaN,0.00,NaN
866,45928.0,0 days 20:50:00.000000003,1.0,71-271-2025,NaN,NaN,NaN,NaN,19.0,LIMPIEZA SISTEMA (PESCADO),...,357.894737,20.0,60.0,GREENOX,NaN,ü,NaN,NaN,0.00,NaN
867,45928.0,0 days 21:00:00,1.0,72-271-2025,NaN,NaN,NaN,NaN,17.0,LIMPIEZA SISTEMA (CAMARÓN),...,282.352941,20.0,60.0,GREENOX,NaN,ü,NaN,NaN,0.00,NaN
868,45928.0,0 days 22:30:00,1.0,07-271-2025,1--2,NaN,NaN,140.0,NaN,NaN,...,831.428571,22.0,45.0,GREENOX,NaN,ü,NaN,NaN,0.00,NaN
869,45928.0,0 days 00:09:59.999999996,1.0,07-271-2025,3--4--5--6++42 sacos,NaN,NaN,322.0,NaN,NaN,...,891.925466,22.0,45.0,GREENOX,NaN,ü,NaN,NaN,0.00,NaN

In [29]:
control.loc[control['COLOR']== 45, "COLOR"] = 4.5

In [30]:
control['OBSERVACIÓN'].value_counts(dropna=False)

OBSERVACIÓN
NaN                                                 616
LIMPIEZA DEL SISTEMA                                 84
LIMPIEZA SISTEMA (CAMARÓN)                           72
LIMPIEZA SISTEMA (PESCADO)                           64
PROTEINA BAJA                                         6
TONO 5                                                5
TONO 4                                                4
SECADO MANUAL                                         4
HUMEDAD ALTA                                          2
PROTEÍNA BAJA                                         2
SECADO AUTOMATICO                                     2
TONO 6                                                1
GRANULOMETRIA ALTA                                    1
HUMEDOS                                               1
TONO 3,5 - PROTEÍNA BAJA                              1
TONO 4 - PROTEÍNA BAJA                                1
HARINA SECA                                           1
GRANOLUMETRIA ALTA SE PASO  POR EL MOLINO GRANDE      1
Name: count, dtype: int64

In [31]:
control[control["COLOR"]<=3]

,FECHA,HORA,TURNO,LOTE,PALLET,PT_25,PT_50,REPROCESO_25,REPROCESO_50,OBSERVACIÓN,...,PPM,FLUJO,VARIADOR,NOMBRE,SIPERNAT_SI,SIPERNAT_NO,INIMHOL_INICIO_KG,INIMHOL_FIN_KG,INIMHOL_TOTAL_KG,INIMHOL_DOSIS_KG/TON
2,45674.0,0 days 06:20:00,1.0,4135-01-2025,3--4 + 50 SACOS,190.0,NaN,NaN,NaN,NaN,...,1705.263158,19.0,40.0,GREENOX,NaN,ü,205.85,203.75,2.10,2.000000
25,45695.0,0 days 14:44:59.999999997,2.0,07-038-2025,5--6,NaN,NaN,140.0,NaN,PROTEÍNA BAJA,...,1268.571429,19.0,40.0,GREENOX,NaN,ü,135.55,133.50,2.05,1.518519
26,45695.0,0 days 17:30:00.000000002,2.0,07-038-2025,7--8--9 + 44 SACOS,NaN,NaN,254.0,NaN,PROTEÍNA BAJA,...,1250.393701,19.0,40.0,GREENOX,NaN,ü,133.40,131.20,2.20,1.257143
28,45696.0,0 days 07:00:00.000000002,2.0,07-039-2025,1--2,NaN,NaN,140.0,NaN,PROTEINA BAJA,...,1668.571429,19.0,40.0,GREENOX,NaN,ü,129.05,124.95,4.10,1.171429
29,45696.0,0 days 07:59:59.999999997,2.0,07-039-2025,3--4,NaN,NaN,140.0,NaN,PROTEINA BAJA,...,1680.000000,19.0,40.0,GREENOX,NaN,ü,124.95,119.10,5.85,1.147059
30,45696.0,0 days 09:00:00,1.0,07-039-2025,5--6,NaN,NaN,140.0,NaN,PROTEINA BAJA,...,1708.571429,19.0,40.0,GREENOX,NaN,ü,119.60,116.25,3.35,2.791667
31,45696.0,0 days 09:45:00,1.0,07-039-2025,7--8,NaN,NaN,140.0,NaN,PROTEINA BAJA,...,1720.000000,19.0,40.0,GREENOX,NaN,ü,116.25,112.20,4.05,1.157143
32,45696.0,0 days 10:30:00,1.0,07-039-2025,9--10,NaN,NaN,140.0,NaN,PROTEINA BAJA,...,1714.285714,19.0,40.0,GREENOX,NaN,ü,112.20,105.90,6.30,1.285714
33,45696.0,0 days 11:50:00.000000003,1.0,07-039-2025,11--12 + 4 SACOS,NaN,NaN,144.0,NaN,PROTEINA BAJA,...,1694.444444,19.0,40.0,GREENOX,NaN,ü,162.95,161.40,1.55,1.550000
124,45736.0,0 days 10:45:00.000000002,1.0,07-079-2025,9---10++2 SACOS,NaN,NaN,142.0,NaN,NaN,...,1921.126761,22.0,42.0,GREENOX,NaN,ü,57.20,53.05,4.15,1.317460

In [40]:
control["color_cat"] = 'col' + '-'+ control["COLOR"].astype(str)

bins = [-np.inf, 3, 4.5, np.inf]
labels = ['bueno', 'medio', 'malo']

# Creamos la nueva columna
control['group_color'] = pd.cut(control['COLOR'], bins=bins, labels=labels)

In [88]:
contl_obs = control.groupby(["CONCENTRADO", 'OBSERVACIÓN']).agg(
    color=('COLOR', 'mean'), 
).reset_index()
contl_obs

   CONCENTRADO                                       OBSERVACIÓN     color
0           NO                              LIMPIEZA DEL SISTEMA  4.416667
1           NO                        LIMPIEZA SISTEMA (CAMARÓN)  4.500000
2           NO                        LIMPIEZA SISTEMA (PESCADO)  5.000000
3           NO                                     PROTEINA BAJA  3.000000
4           NO                                     PROTEÍNA BAJA  3.000000
5           NO                          TONO 3,5 - PROTEÍNA BAJA  3.500000
6           NO                            TONO 4 - PROTEÍNA BAJA  4.000000
7           NO                                            TONO 5  5.000000
8           SI  GRANOLUMETRIA ALTA SE PASO  POR EL MOLINO GRANDE  4.000000
9           SI                                GRANULOMETRIA ALTA  4.000000
10          SI                                       HARINA SECA  4.000000
11          SI                                      HUMEDAD ALTA  4.000000
12          SI                                           HUMEDOS  4.000000
13          SI                              LIMPIEZA DEL SISTEMA  4.562500
14          SI                        LIMPIEZA SISTEMA (CAMARÓN)  4.268116
15          SI                        LIMPIEZA SISTEMA (PESCADO)  4.852459
16          SI                                 SECADO AUTOMATICO  4.000000
17          SI                                     SECADO MANUAL  4.000000
18          SI                                            TONO 4  4.000000
19          SI                                            TONO 5  4.500000
20          SI                                            TONO 6  4.000000

In [89]:
plot_heatmap(

    df=contl_obs,
    x_col="OBSERVACIÓN",
    y_col="CONCENTRADO",
    value_col='color'
)

In [33]:
control.groupby('color_cat', dropna=False).agg(
    protein_avg=('PROTEINA', 'mean'),
    protein_median=('PROTEINA', 'median'),
    moisture_avg=('HUM', 'mean'),
    moisture_median=('HUM', 'median'),
    temp_avg=('TEMP', 'mean'),
    temp_median=('TEMP', 'median'),
    color_avg=('COLOR', 'mean'),
    color_median=('COLOR', 'median'),
    grasa_avg=( 'GRASA', 'mean'),
    grasa_median=('GRASA', 'median'),
    cenizas_avg=('CENIZA', 'mean'),
    cenizas_median=('CENIZA', 'median'),
    granulometria_avg=('GRANULOMETRIA', 'mean'),
    granulometria_median=('GRANULOMETRIA', 'median'),
    antioxidante_avg=('ANTIOXIDANTE_TOTAL_KG', 'mean'),
    antioxidante_median=('ANTIOXIDANTE_TOTAL_KG', 'median'),
)

,protein_avg,protein_median,moisture_avg,moisture_median,temp_avg,temp_median,color_avg,color_median,grasa_avg,grasa_median,cenizas_avg,cenizas_median,granulometria_avg,granulometria_median,antioxidante_avg,antioxidante_median
color_cat,,,,,,,,,,,,,,,,
col-0.0,NaN,NaN,7.580000,7.580,40.400000,40.40,0.0,0.0,NaN,NaN,NaN,NaN,38.820000,38.820,17.050000,17.050
col-3.0,49.364444,49.45,8.253333,8.220,40.877778,40.80,3.0,3.0,NaN,NaN,NaN,NaN,38.505556,38.550,15.638889,15.000
col-3.5,51.370000,51.50,7.276000,7.335,41.270000,41.35,3.5,3.5,NaN,NaN,NaN,NaN,36.003000,37.125,15.285000,14.725
col-4.0,51.181228,51.35,7.919180,7.970,40.836574,40.80,4.0,4.0,NaN,NaN,NaN,NaN,34.979761,34.550,18.073487,15.200
col-4.5,52.556667,52.30,7.521982,7.640,39.825586,39.80,4.5,4.5,NaN,NaN,NaN,NaN,33.263423,32.450,9.443243,4.300
col-5.0,51.150000,51.15,7.416386,7.360,39.359036,39.40,5.0,5.0,NaN,NaN,NaN,NaN,32.505181,31.260,3.700833,3.250
col-6.0,54.450000,54.45,5.370000,5.370,40.000000,40.00,6.0,6.0,NaN,NaN,NaN,NaN,24.300000,24.300,1.800000,1.800
col-nan,NaN,NaN,8.920000,8.920,41.900000,41.90,NaN,NaN,NaN,NaN,NaN,NaN,33.450000,33.450,14.350000,14.350

In [41]:
control.groupby('group_color', dropna=False).agg(
    protein_avg=('PROTEINA', 'mean'),
    protein_median=('PROTEINA', 'median'),
    moisture_avg=('HUM', 'mean'),
    moisture_median=('HUM', 'median'),
    temp_avg=('TEMP', 'mean'),
    temp_median=('TEMP', 'median'),
    color_avg=('COLOR', 'mean'),
    color_median=('COLOR', 'median'),
    grasa_avg=( 'GRASA', 'mean'),
    grasa_median=('GRASA', 'median'),
    cenizas_avg=('CENIZA', 'mean'),
    cenizas_median=('CENIZA', 'median'),
    granulometria_avg=('GRANULOMETRIA', 'mean'),
    granulometria_median=('GRANULOMETRIA', 'median'),
    antioxidante_avg=('ANTIOXIDANTE_TOTAL_KG', 'mean'),
    antioxidante_median=('ANTIOXIDANTE_TOTAL_KG', 'median'),
)

/var/folders/1g/77kw2x4j5678s_87_sqc1fpc0000gp/T/ipykernel_77801/3628019760.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

,protein_avg,protein_median,moisture_avg,moisture_median,temp_avg,temp_median,color_avg,color_median,grasa_avg,grasa_median,cenizas_avg,cenizas_median,granulometria_avg,granulometria_median,antioxidante_avg,antioxidante_median
group_color,,,,,,,,,,,,,,,,
bueno,49.364444,49.45,8.186000,8.10,40.830000,40.65,2.700000,3.0,NaN,NaN,NaN,NaN,38.53700,38.685,15.780000,15.025
medio,51.267143,51.37,7.853312,7.90,40.696281,40.80,4.065415,4.0,NaN,NaN,NaN,NaN,34.74563,34.025,16.796490,15.000
malo,52.800000,52.80,7.392024,7.36,39.366667,39.40,5.011765,5.0,NaN,NaN,NaN,NaN,32.40750,31.255,3.678471,3.200
NaN,NaN,NaN,8.920000,8.92,41.900000,41.90,NaN,NaN,NaN,NaN,NaN,NaN,33.45000,33.450,14.350000,14.350

In [39]:
for cl in cols_num:
    f = plot_statistical_strip(
            df=control,
            x_col="color_cat",
            y_col=cl,
            title=cl)
    f.show()

In [43]:
for cl in cols_num:
    f = plot_statistical_strip(
            df=control,
            x_col="group_color",
            y_col=cl,
            title=cl)
    f.show()

In [50]:
planta2 = pd.read_excel("../raw/fortidex/SACO PATRON HNA CAM2025 (15) (1).xlsb", sheet_name="S.P.HC-2025", engine="pyxlsb")

In [58]:
planta2[['FECHA DE PRODUCCIÓN', 'TURNO', 'LOTE DE PRODUCCIÓN',
       'SECUENCIA DE PALLETS', 'NÚMERO DE TOLVADA', 'T. SECADO', 'SACOS',
       'PRESENT KG', 'CRITERIO', 'HUMEDAD', 'PROTEINA', 'FFA',
       'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'TVN', 'SOLUBLE', 'TONO', 'AOX',
       'ACIDO', 'NITRITOS', 'SALMONELLA', 'ENSAYO', 'ASTAXANTINA']]


planta2['FECHA DE PRODUCCIÓN'] = pd.to_numeric(planta2['FECHA DE PRODUCCIÓN'], errors='coerce')
planta2 = planta2[planta2["FECHA DE PRODUCCIÓN"].notna()]

cls_num_plant2 = [
       'SACOS',
       'PRESENT KG', 'HUMEDAD', 'PROTEINA', 'FFA',
       'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'TVN',  'TONO', 'AOX',
       'ACIDO', 'NITRITOS', 'SALMONELLA',
]
for cl in cls_num_plant2:
       planta2[cl] = pd.to_numeric(planta2[cl], errors='coerce')

In [59]:
planta2[['FECHA DE PRODUCCIÓN', 'TURNO', 'LOTE DE PRODUCCIÓN',
       'SECUENCIA DE PALLETS', 'NÚMERO DE TOLVADA', 'T. SECADO', 'SACOS',
       'PRESENT KG', 'CRITERIO', 'HUMEDAD', 'PROTEINA', 'FFA',
       'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'TVN', 'SOLUBLE', 'TONO', 'AOX',
       'ACIDO', 'NITRITOS', 'SALMONELLA', 'ENSAYO', 'ASTAXANTINA']]

,FECHA DE PRODUCCIÓN,TURNO,LOTE DE PRODUCCIÓN,SECUENCIA DE PALLETS,NÚMERO DE TOLVADA,T. SECADO,SACOS,PRESENT KG,CRITERIO,HUMEDAD,...,TEMP.ºC,TVN,SOLUBLE,TONO,AOX,ACIDO,NITRITOS,SALMONELLA,ENSAYO,ASTAXANTINA
0,45614.0,NaN,07-323-2024,3 AL 5,1.0,RD/FD,70.0,25.0,PARA MEZCLA,6.68,...,39.8,NaN,SI,3.0,3.040000,1.36,22.08,NaN,NaN,NaN
1,45614.0,NaN,07-323-2024,6 AL 7 + 34 SACOS,1.0,RD/FD,174.0,25.0,PARA MEZCLA,6.88,...,40.0,NaN,SI,3.5,2.940000,1.60,20.46,NaN,NaN,NaN
2,45635.0,NaN,07-344-2024,1 AL 3,1.0,RD/FD,210.0,25.0,PARA MEZCLA,5.62,...,39.9,NaN,SI,4.0,3.390000,1.43,20.46,NaN,NaN,NaN
3,45635.0,NaN,07-344-2024,4 AL 6,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.90,...,40.2,NaN,SI,4.0,2.720000,2.48,20.46,NaN,NaN,NaN
4,45635.0,NaN,07-344-2024,7 AL 9,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.46,...,41.0,NaN,SI,4.0,2.840000,1.46,20.46,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,45922.0,1.0,07-265-2025,29--30--31--+64 sacos,9.0,SD/FD,274.0,25.0,NaN,8.78,...,41.2,NaN,SI,4.0,4.500000,1.98,NaN,NaN,NaN,NaN
630,45923.0,1.0,07-266-2025,1--2,1.0,SD/FD,140.0,25.0,NaN,8.88,...,40.4,NaN,SI,4.5,4.185714,1.23,NaN,NaN,NaN,NaN
631,45923.0,1.0,07-266-2025,3--4--5,2.0,SD/FD,210.0,25.0,NaN,8.55,...,41.0,NaN,SI,4.5,4.133333,1.25,NaN,NaN,NaN,NaN
632,45923.0,1.0,07-266-2025,6--7--8,3.0,SD/FD,210.0,25.0,NaN,9.18,...,41.9,NaN,SI,4.5,4.133333,1.25,NaN,NaN,NaN,NaN
633,45923.0,1.0,07-266-2025,9--10--11--12--44 SACOS,4.0,SD/FD,324.0,25.0,NaN,9.22,...,41.4,NaN,SI,4.5,4.660494,1.65,NaN,NaN,NaN,NaN

In [82]:
planta_tolva_criterio = planta2.groupby(["T. SECADO", "CRITERIO"]).agg(tono=("TONO","median")).reset_index()
planta_tolva_criterio

   T. SECADO                                     CRITERIO  tono
0      RD/FD                             DESPACHO DIRECTO   4.0
1      RD/FD                            MEZCLA POR CENIZA   4.0
2      RD/FD                           MEZCLA POR NITRITO   4.0
3      RD/FD                  MEZCLA POR NITRITO Y CENIZA   4.0
4      RD/FD                          MEZCLA POR NITRITOS   4.0
5      RD/FD                 MEZCLA POR NITRITOS Y CENIZA   4.0
6      RD/FD               MEZCLA POR NITRITOS Y PROTEINA   4.0
7      RD/FD              MEZCLA POR NITRITOS Y PROTEINA    4.0
8      RD/FD              MEZCLA POR NITRITOS Y TONALIDAD   4.5
9      RD/FD       MEZCLA POR NITRITOS, PROTEINA Y CENIZA   4.0
10     RD/FD                          MEZCLA POR PROTEINA   4.0
11     RD/FD                 MEZCLA POR PROTEINA Y CENIZA   4.0
12     RD/FD      MEZCLA POR PROTEINA, CENIZA Y TONALIDAD   4.5
13     RD/FD                         MEZCLA POR TONALIDAD   4.5
14     RD/FD                              MEZCLA POR TONO   4.5
15     RD/FD                    MEZCLA POR TONO Y NITRITO   4.5
16     RD/FD                   MEZCLA POR TONO Y PROTEINA   4.5
17     RD/FD          MEZCLA POR TONO, NITRITO Y PROTEINA   4.5
18     RD/FD  MEZCLA POR TONO, NITRITO, CENIZA Y PROTEINA   4.5
19     RD/FD                    MEZCLA POR TONO, NITRITOS   4.5
20     RD/FD         MEZCLA POR TONO, NITRITOS Y PROTEINA   4.5
21     RD/FD                                  PARA MEZCLA   4.0
22        SD                             DESPACHO DIRECTO   4.0
23        SD                MEZCLA POR CENIZA Y TONALIDAD   4.5
24        SD                 MEZCLA POR PROTEINA Y CENIZA   4.5
25        SD              MEZCLA POR PROTEINA Y TONALIDAD   4.5
26        SD      MEZCLA POR PROTEINA, CENIZA Y TONALIDAD   4.5
27        SD                         MEZCLA POR TONALIDAD   4.5
28        SD                MEZCLA POR TONALIDAD Y CENIZA   4.5
29        SD              MEZCLA POR TONALIDAD Y PROTEINA   4.5
30        SD                                  PARA MEZCLA   3.5
31     SD/FD                             DESPACHO DIRECTO   4.5
32     SD/FD                        MEZCLA POR  TONALIDAD   4.5
33     SD/FD                            MEZCLA POR CENIZA   4.5
34     SD/FD                MEZCLA POR CENIZA Y TONALIDAD   4.5
35     SD/FD                          MEZCLA POR NITRITOS   4.5
36     SD/FD                 MEZCLA POR PROTEINA Y CENIZA   4.5
37     SD/FD      MEZCLA POR PROTEINA, CENIZA Y TONALIDAD   4.5
38     SD/FD                         MEZCLA POR TONALIDAD   4.5
39     SD/FD                MEZCLA POR TONALIDAD Y CENIZA   4.5
40     SD/FD              MEZCLA POR TONALIDAD Y PROTEINA   4.5
41     SD/FD                                  PARA MEZCLA   4.0
42     SD/FD                          REPROCESO TONALIDAD   5.0

In [83]:
plot_heatmap

<function core.viz.plot_heatmap(df: pandas.core.frame.DataFrame, x_col: str, y_col: str, value_col: str, secondary_col: Optional[str] = None, secondary_aggfunc: str = 'sum', aggfunc: str = 'mean', x_order: Optional[List[str]] = None, y_order: Optional[List[str]] = None, value_unit: str = '', unit_position: str = 'suffix', decimals_value: int = 2, decimals_secondary: int = 1, secondary_prefix: str = '', colorscale: Union[str, List[Tuple[float, str]]] = ['#1C8074', '#666666', '#E4572E', '#29B6F6', '#FFA726'], zmin: Optional[float] = None, zmax: Optional[float] = None, zmid: Optional[float] = None, title: str = '', show_secondary_labels: bool = True, secondary_position: str = 'bottom', font_color: str = 'black', center_font_size: int = 14, secondary_font_size: int = 10, width: int = 800, height: int = 500, transparent_bg: bool = True, output_path: Optional[str] = None) -> plotly.graph_objs._figure.Figure>

In [84]:
plot_heatmap(
    df=planta_tolva_criterio,
    x_col="T. SECADO",
    y_col="CRITERIO",
    value_col="tono",
    width=1000,
    height=1000,
    
)

In [ ]:
planta2["color_cat"] = 'col' + '-'+ planta2["TONO"].astype(str)
bins = [-np.inf, 3, 4.5, np.inf]
labels = ['bueno', 'medio', 'malo']
planta2['group_color'] = pd.cut(planta2['TONO'], bins=bins, labels=labels)

planta2["tolva"] = 'tolva' + '-'+planta2['NÚMERO DE TOLVADA'].astype(int).astype(str)

In [71]:
planta2

,FECHA DE PRODUCCIÓN,TURNO,LOTE DE PRODUCCIÓN,SECUENCIA DE PALLETS,NÚMERO DE TOLVADA,T. SECADO,SACOS,PRESENT KG,CRITERIO,HUMEDAD,...,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,color_cat,group_color,tolva
0,45614.0,NaN,07-323-2024,3 AL 5,1.0,RD/FD,70.0,25.0,PARA MEZCLA,6.68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-3.0,bueno,tolva-1
1,45614.0,NaN,07-323-2024,6 AL 7 + 34 SACOS,1.0,RD/FD,174.0,25.0,PARA MEZCLA,6.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-3.5,medio,tolva-1
2,45635.0,NaN,07-344-2024,1 AL 3,1.0,RD/FD,210.0,25.0,PARA MEZCLA,5.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.0,medio,tolva-1
3,45635.0,NaN,07-344-2024,4 AL 6,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.0,medio,tolva-1
4,45635.0,NaN,07-344-2024,7 AL 9,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.0,medio,tolva-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,45922.0,1.0,07-265-2025,29--30--31--+64 sacos,9.0,SD/FD,274.0,25.0,NaN,8.78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.0,medio,tolva-9
630,45923.0,1.0,07-266-2025,1--2,1.0,SD/FD,140.0,25.0,NaN,8.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.5,medio,tolva-1
631,45923.0,1.0,07-266-2025,3--4--5,2.0,SD/FD,210.0,25.0,NaN,8.55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.5,medio,tolva-2
632,45923.0,1.0,07-266-2025,6--7--8,3.0,SD/FD,210.0,25.0,NaN,9.18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.5,medio,tolva-3
633,45923.0,1.0,07-266-2025,9--10--11--12--44 SACOS,4.0,SD/FD,324.0,25.0,NaN,9.22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,col-4.5,medio,tolva-4

In [64]:
for cl in cls_num_plant2:
    f = plot_statistical_strip(
            df=planta2,
            x_col="color_cat",
            y_col=cl,
            title=cl)
    f.show()

In [65]:
for cl in cls_num_plant2:
    f = plot_statistical_strip(
            df=planta2,
            x_col="group_color",
            y_col=cl,
            title=cl)
    f.show()