In [71]:
import pandas as pd
import numpy as np
import sys
import os
sys.path.append(os.path.abspath(".."))
from core.viz import plot_bar, plot_dynamic_trends, plot_line, plot_corr_triangle, plot_scatter, plot_statistical_strip, plot_heatmap
from core.s3 import S3AssetManager

In [72]:
notebook_name = "fortidex_harina_camaron"
s3 = S3AssetManager(notebook_name=notebook_name)

In [73]:
planta1 = pd.read_excel(
    "../raw/fortidex/HUMEDADES EN LINEA PRO CAMARÓN 2025.xlsb",
     sheet_name="CLEAR",
     #skiprows=8,
     engine="pyxlsb")

In [74]:
planta1['FECHA'] = pd.to_numeric(planta1['FECHA'], errors='coerce')
#planta1['FECHA'] = pd.to_datetime(planta1['FECHA'], unit='D')
planta1['HORA'] = pd.to_timedelta(planta1['HORA'], unit='D', errors='coerce')
planta1 = planta1[planta1["FECHA"].notna()]

In [75]:
cols_num = [
'PT_25', 'PT_50',
'REPROCESO_25', 'REPROCESO_50',
'HUM', 'PROTEINA',
'GRASA', 'CENIZA', 'GRANULOMETRIA',
'TEMP', 'TEMP_POND', 
'COLOR', 'DOSIS', 'PT_SACOS', 'PT_TON',
'ANTIOXIDANTE_INICIO_KG', 
'ANTIOXIDANTE_FIN_KG',
'ANTIOXIDANTE_TOTAL_KG',
'DOSIS_KG_TON', 'PPM', 'FLUJO', 'VARIADOR',
'INIMHOL_INICIO_KG',
'INIMHOL_FIN_KG',
'INIMHOL_TOTAL_KG',
'INIMHOL_DOSIS_KG/TON'
]

In [76]:
for cl_num in cols_num:
    planta1[cl_num] = pd.to_numeric(planta1[cl_num], errors="coerce")

In [77]:
planta1.loc[planta1['COLOR']== 45, "COLOR"] = 4.5

In [78]:

mapeo_categorias = {
    # Limpieza
    'LIMPIEZA DEL SISTEMA': 'Limpieza',
    'LIMPIEZA SISTEMA (PESCADO)': 'Limpieza',
    'LIMPIEZA SISTEMA (CAMARÓN)': 'Limpieza',
    
    # Proteína (Unificamos tonos con baja proteína en la categoría de la falla)
    'PROTEÍNA BAJA': 'Baja Proteína',
    'PROTEINA BAJA': 'Baja Proteína',
    'TONO 4 - PROTEÍNA BAJA': 'Baja Proteína',
    'TONO 3,5 - PROTEÍNA BAJA': 'Baja Proteína',
    
    # Humedad
    'HUMEDAD ALTA': 'Problemas de Humedad',
    'HUMEDOS': 'Problemas de Humedad',
    'HARINA SECA': 'Harina Seca', # O puedes unirlo a 'Problemas de Humedad' si es un defecto
    
    # Granulometría
    'GRANULOMETRIA ALTA': 'Granulometría Alta',
    'GRANOLUMETRIA ALTA SE PASO  POR EL MOLINO GRANDE': 'Granulometría Alta',
    
    # Tonos (Solo los que no tienen defectos explícitos)
    'TONO 4': 'Clasificación Tono',
    'TONO 5': 'Clasificación Tono',
    'TONO 6': 'Clasificación Tono',
    
    # Secado
    'SECADO AUTOMATICO': 'Proceso de Secado',
    'SECADO MANUAL': 'Proceso de Secado'
}
planta1['categoria_observacion'] = planta1['OBSERVACIÓN'].map(mapeo_categorias)
planta1["color_cat"] = 'col' + '-'+ planta1["COLOR"].astype(str)

bins = [-np.inf, 3, 4.5, np.inf]
labels = ['bueno', 'medio', 'malo']

# Creamos la nueva columna
planta1['group_color'] = pd.cut(planta1['COLOR'], bins=bins, labels=labels)

In [79]:
contl_obs = planta1.groupby(["CONCENTRADO", 'categoria_observacion'], as_index=False).agg(
    color=('COLOR', 'mean'), 
    count=('LOTE', 'count')
).reset_index()
contl_obs

   index CONCENTRADO categoria_observacion     color  count
0      0          NO         Baja Proteína  3.150000     10
1      1          NO    Clasificación Tono  5.000000      1
2      2          NO              Limpieza  4.527778     18
3      3          SI    Clasificación Tono  4.222222      9
4      4          SI    Granulometría Alta  4.000000      2
5      5          SI           Harina Seca  4.000000      1
6      6          SI              Limpieza  4.549505    202
7      7          SI  Problemas de Humedad  4.000000      3
8      8          SI     Proceso de Secado  4.000000      6

In [80]:
f = plot_heatmap(
    df=contl_obs,
    x_col="categoria_observacion", #"OBSERVACIÓN",
    y_col="CONCENTRADO",
    value_col='color',
    secondary_col='count',
    secondary_aggfunc='sum',
    decimals_secondary=0,
    width=1000,
    height=400,
    title="Color por variable de concentrado y observación"
)
f.show()
s3.save_plotly_html(f, "heat_concentrado_observacion.html")

In [81]:
planta1_group = planta1.groupby('color_cat', dropna=False).agg(
    count_row=("LOTE", "count"),
    #protein_avg=('PROTEINA', 'mean'),
    protein_median=('PROTEINA', 'median'),
    #moisture_avg=('HUM', 'mean'),
    moisture_median=('HUM', 'median'),
    #temp_avg=('TEMP', 'mean'),
    temp_median=('TEMP', 'median'),
    #color_avg=('COLOR', 'mean'),
    color_median=('COLOR', 'median'),
    #grasa_avg=( 'GRASA', 'mean'),
    grasa_median=('GRASA', 'median'),
    #cenizas_avg=('CENIZA', 'mean'),
    cenizas_median=('CENIZA', 'median'),
    #granulometria_avg=('GRANULOMETRIA', 'mean'),
    granulometria_median=('GRANULOMETRIA', 'median'),
    #antioxidante_avg=('ANTIOXIDANTE_TOTAL_KG', 'mean'),
    antioxidante_median=('ANTIOXIDANTE_TOTAL_KG', 'median'),
).reset_index().round(2)

s3.save_dataframe(planta1_group, 'planta1_group.csv')
planta1_group

/Users/juandavidrincon/Documents/hawking/.venv/lib/python3.13/site-packages/fsspec/registry.py:301: UserWarning:

Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

,color_cat,count_row,protein_median,moisture_median,temp_median,color_median,grasa_median,cenizas_median,granulometria_median,antioxidante_median
0,col-0.0,1,NaN,7.58,40.40,0.0,NaN,NaN,38.82,17.05
1,col-3.0,9,49.45,8.22,40.80,3.0,NaN,NaN,38.55,15.00
2,col-3.5,10,51.50,7.34,41.35,3.5,NaN,NaN,37.12,14.72
3,col-4.0,633,51.35,7.97,40.80,4.0,NaN,NaN,34.55,15.20
4,col-4.5,107,52.30,7.64,39.80,4.5,NaN,NaN,32.45,4.30
5,col-5.0,84,51.15,7.36,39.40,5.0,NaN,NaN,31.26,3.25
6,col-6.0,1,54.45,5.37,40.00,6.0,NaN,NaN,24.30,1.80
7,col-nan,1,NaN,8.92,41.90,NaN,NaN,NaN,33.45,14.35

In [88]:
# Definimos la lógica del CV para no repetirla tanto
cv_func = lambda x: (x.std() / x.mean()) * 100 if x.mean() != 0 else 0

resultado = planta1.groupby('group_color').agg(
     count_row=("LOTE", "count"),
    # --- PROTEÍNA ---
    protein_median=('PROTEINA', 'median'),
    protein_cv=('PROTEINA', cv_func),
    
    # --- HUMEDAD ---
    moisture_median=('HUM', 'median'),
    moisture_cv=('HUM', cv_func),
    
    # --- TEMPERATURA ---
    temp_median=('TEMP', 'median'),
    temp_cv=('TEMP', cv_func),
    
    # --- GRASA ---
    #grasa_median=('GRASA', 'median'),
    #grasa_cv=('GRASA', cv_func),
    
    # --- DEMÁS VARIABLES (Solo medianas por ahora, agrega CV si necesitas) ---
    #color_median=('COLOR', 'median'),
   # cenizas_median=('CENIZA', 'median'),
    granulometria_median=('GRANULOMETRIA', 'median'),
    antioxidante_median=('ANTIOXIDANTE_TOTAL_KG', 'median'),
)
resultado = resultado.reset_index().round(2)
s3.save_dataframe(resultado, "summary_pl1.csv")
resultado

/var/folders/1g/77kw2x4j5678s_87_sqc1fpc0000gp/T/ipykernel_91592/2484672128.py:4: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

,group_color,count_row,protein_median,protein_cv,moisture_median,moisture_cv,temp_median,temp_cv,granulometria_median,antioxidante_median
0,bueno,10,49.45,1.24,8.10,7.06,40.65,2.51,38.68,15.03
1,medio,750,51.37,2.75,7.90,10.73,40.80,2.55,34.02,15.00
2,malo,85,52.80,4.42,7.36,13.50,39.40,1.35,31.26,3.20

In [83]:
for cl in cols_num:
    f = plot_statistical_strip(
            df=planta1,
            x_col="color_cat",
            y_col=cl,
            title=f"<b> color vs {cl.replace('_', ' ').lower()} </b>",
            x_title="Color",
            y_title=f"{cl.replace('', ' ').lower()}")
    f.show()
    name = f"pl1_boxplot_color_{cl}.html"
    print(name)
    s3.save_plotly_html(f, name)

pl1_boxplot_color_PT_25.html

pl1_boxplot_color_PT_50.html

pl1_boxplot_color_REPROCESO_25.html

pl1_boxplot_color_REPROCESO_50.html

pl1_boxplot_color_HUM.html

pl1_boxplot_color_PROTEINA.html

pl1_boxplot_color_GRASA.html

pl1_boxplot_color_CENIZA.html

pl1_boxplot_color_GRANULOMETRIA.html

pl1_boxplot_color_TEMP.html

pl1_boxplot_color_TEMP_POND.html

pl1_boxplot_color_COLOR.html

pl1_boxplot_color_DOSIS.html

pl1_boxplot_color_PT_SACOS.html

pl1_boxplot_color_PT_TON.html

pl1_boxplot_color_ANTIOXIDANTE_INICIO_KG.html

pl1_boxplot_color_ANTIOXIDANTE_FIN_KG.html

pl1_boxplot_color_ANTIOXIDANTE_TOTAL_KG.html

pl1_boxplot_color_DOSIS_KG_TON.html

pl1_boxplot_color_PPM.html

pl1_boxplot_color_FLUJO.html

pl1_boxplot_color_VARIADOR.html

pl1_boxplot_color_INIMHOL_INICIO_KG.html

pl1_boxplot_color_INIMHOL_FIN_KG.html

pl1_boxplot_color_INIMHOL_TOTAL_KG.html

pl1_boxplot_color_INIMHOL_DOSIS_KG/TON.html

In [89]:
for cl in cols_num:
    f = plot_statistical_strip(
            df=planta1,
            x_col="group_color",
            y_col=cl,
            title=f"<b> color vs {cl.replace('_', ' ').lower()} </b>",
            x_title="Color Agrupado", 
            )
    f.show() 
    name = f"pl1_boxplot_color_{cl}.html"
    print(name)
    s3.save_plotly_html(f, name)

pl1_boxplot_color_PT_25.html

pl1_boxplot_color_PT_50.html

pl1_boxplot_color_REPROCESO_25.html

pl1_boxplot_color_REPROCESO_50.html

pl1_boxplot_color_HUM.html

pl1_boxplot_color_PROTEINA.html

pl1_boxplot_color_GRASA.html

pl1_boxplot_color_CENIZA.html

pl1_boxplot_color_GRANULOMETRIA.html

pl1_boxplot_color_TEMP.html

pl1_boxplot_color_TEMP_POND.html

pl1_boxplot_color_COLOR.html

pl1_boxplot_color_DOSIS.html

pl1_boxplot_color_PT_SACOS.html

pl1_boxplot_color_PT_TON.html

pl1_boxplot_color_ANTIOXIDANTE_INICIO_KG.html

pl1_boxplot_color_ANTIOXIDANTE_FIN_KG.html

pl1_boxplot_color_ANTIOXIDANTE_TOTAL_KG.html

pl1_boxplot_color_DOSIS_KG_TON.html

pl1_boxplot_color_PPM.html

pl1_boxplot_color_FLUJO.html

pl1_boxplot_color_VARIADOR.html

pl1_boxplot_color_INIMHOL_INICIO_KG.html

pl1_boxplot_color_INIMHOL_FIN_KG.html

pl1_boxplot_color_INIMHOL_TOTAL_KG.html

pl1_boxplot_color_INIMHOL_DOSIS_KG/TON.html

In [91]:
planta1.columns

Index(['FECHA', 'HORA', 'TURNO', 'LOTE', 'PALLET', 'PT_25', 'PT_50',
       'REPROCESO_25', 'REPROCESO_50', 'OBSERVACIÓN', 'HUM', 'PROTEINA',
       'GRASA', 'CENIZA', 'GRANULOMETRIA', 'TEMP', 'TEMP_POND', 'TVN',
       'CONCENTRADO', 'COLOR', 'DOSIS', 'PT_SACOS', 'PT_TON',
       'ANTIOXIDANTE_INICIO_KG', 'ANTIOXIDANTE_FIN_KG',
       'ANTIOXIDANTE_TOTAL_KG', 'DOSIS_KG_TON', 'PPM', 'FLUJO', 'VARIADOR',
       'NOMBRE', 'SIPERNAT_SI', 'SIPERNAT_NO', 'INIMHOL_INICIO_KG',
       'INIMHOL_FIN_KG', 'INIMHOL_TOTAL_KG', 'INIMHOL_DOSIS_KG/TON',
       'categoria_observacion', 'color_cat', 'group_color'],
      dtype='object')

In [103]:
planta1[['COLOR', 'HUM', 'PROTEINA','GRANULOMETRIA', 'TEMP','PPM']]

     COLOR   HUM  PROTEINA  GRANULOMETRIA  TEMP          PPM
0      4.0  4.90       NaN          22.50  39.0   530.434783
1      3.5  6.79     51.35          28.00  41.2  1811.428571
2      3.0  8.22     50.25          39.13  41.0  1705.263158
3      4.0  4.30       NaN          26.10  40.0   390.476190
4      4.0  4.62       NaN          27.12  40.2  1895.652174
..     ...   ...       ...            ...   ...          ...
865    4.0  8.08       NaN          44.22  40.9   840.944882
866    5.0  6.45       NaN          18.36  39.9   357.894737
867    4.5  7.98       NaN          37.45  39.7   282.352941
868    4.0  9.30       NaN          44.15  40.2   831.428571
869    4.0  6.86       NaN          42.25  41.0   891.925466

[868 rows x 6 columns]

In [122]:

import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeRegressor, export_text




def procesar_clustering(df, features, n_clusters=3, pesos_personalizados=None):
    """
    Ejecuta el pipeline completo: Limpieza -> Escalado -> Pesos -> K-Means -> PCA.
    """
    # 1. Preparación
    data = df[features].copy()
    data = data.dropna(axis=1, how='all') # Eliminar columnas vacías
    cols_actuales = data.columns.tolist()
    
    # 2. Imputación (Rellenar huecos con la mediana)
    imputer = SimpleImputer(strategy='median')
    data_imputed = imputer.fit_transform(data)
    
    # 3. Escalado
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data_imputed)
    
    # 4. Aplicar Pesos (Truco para forzar reglas de negocio)
    if pesos_personalizados:
        for col, peso in pesos_personalizados.items():
            if col in cols_actuales:
                idx = cols_actuales.index(col)
                data_scaled[:, idx] = data_scaled[:, idx] * peso
                
    # 5. K-Means
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    clusters = kmeans.fit_predict(data_scaled)
    
    # 6. PCA (Para graficar en 2D)
    pca = PCA(n_components=2)
    componentes = pca.fit_transform(data_scaled)
    
    # 7. Armar DataFrame Final
    df_out = df.copy()
    df_out['Cluster'] = clusters # Numérico (útil para ordenamiento)
    df_out['Cluster_Label'] = "Grupo " + df_out['Cluster'].astype(str) # Texto (útil para Scatter)
    df_out['PC1'] = componentes[:, 0]
    df_out['PC2'] = componentes[:, 1]
    
    # 8. Calcular Medias por Cluster (Para Hover y Análisis)
    # Esto agrega columnas 'Media_COLOR', 'Media_PROTEINA', etc.
    promedios = df_out.groupby('Cluster')[cols_actuales].transform('mean')
    promedios.columns = [f"Media_{c}" for c in promedios.columns]
    
    df_out = pd.concat([df_out, promedios], axis=1)
    
    return df_out

In [125]:
variables = ['PROTEINA', 'HUM', 'TEMP', 'COLOR', 'GRANULOMETRIA', 'PPM']
df_final = procesar_clustering(planta1, variables, n_clusters=3, pesos_personalizados=None)

cls_group = ["Cluster_Label",  "Media_COLOR", "Media_PROTEINA", "Media_HUM", "Media_TEMP", "Media_GRANULOMETRIA", "Media_PPM"]
plant1_summary = df_final[cls_group].drop_duplicates().round(2).sort_values('Cluster_Label')
s3.save_dataframe(plant1_summary, "plant1_summary_group.csv")
plant1_summary

,Cluster_Label,Media_COLOR,Media_PROTEINA,Media_HUM,Media_TEMP,Media_GRANULOMETRIA,Media_PPM
1,Grupo 0,3.89,50.90,8.00,40.85,39.11,1684.82
12,Grupo 1,4.03,51.28,7.95,40.89,34.32,828.46
0,Grupo 2,4.69,52.63,7.24,39.35,31.95,626.79

In [126]:
f = plot_scatter(
df=df_final,
x_col='PC1',
y_col='PC2', 
group_col='Cluster_Label',
hover_data_cols=["LOTE", 'Media_PROTEINA', 'Media_HUM', 'Media_TEMP', 'Media_COLOR', 'Media_GRANULOMETRIA', 'Media_PPM'],
title='<b>Mapa de Clusters (PCA)</b><br><i>Agrupación por similitud de proceso</i>'
)
f.show()
s3.save_plotly_html(f, "componentes_planta1.html")

In [155]:
for cl in cols_num:
    f = plot_statistical_strip(
            df=df_final,
            x_col="Cluster_Label",
            y_col=cl,
            title=f"<b> color vs {cl.replace('_', ' ').lower()} </b>",
            x_title="Color Agrupado", 
            )
    f.show() 
    name = f"pl1_boxplot_color_{cl}.html"
    print(name)
    s3.save_plotly_html(f, name)

pl1_boxplot_color_PT_25.html

pl1_boxplot_color_PT_50.html

pl1_boxplot_color_REPROCESO_25.html

pl1_boxplot_color_REPROCESO_50.html

pl1_boxplot_color_HUM.html

pl1_boxplot_color_PROTEINA.html

pl1_boxplot_color_GRASA.html

pl1_boxplot_color_CENIZA.html

pl1_boxplot_color_GRANULOMETRIA.html

pl1_boxplot_color_TEMP.html

pl1_boxplot_color_TEMP_POND.html

pl1_boxplot_color_COLOR.html

pl1_boxplot_color_DOSIS.html

pl1_boxplot_color_PT_SACOS.html

pl1_boxplot_color_PT_TON.html

pl1_boxplot_color_ANTIOXIDANTE_INICIO_KG.html

pl1_boxplot_color_ANTIOXIDANTE_FIN_KG.html

pl1_boxplot_color_ANTIOXIDANTE_TOTAL_KG.html

pl1_boxplot_color_DOSIS_KG_TON.html

pl1_boxplot_color_PPM.html

pl1_boxplot_color_FLUJO.html

pl1_boxplot_color_VARIADOR.html

pl1_boxplot_color_INIMHOL_INICIO_KG.html

pl1_boxplot_color_INIMHOL_FIN_KG.html

pl1_boxplot_color_INIMHOL_TOTAL_KG.html

pl1_boxplot_color_INIMHOL_DOSIS_KG/TON.html

In [127]:
planta2 = pd.read_excel("../raw/fortidex/SACO PATRON HNA CAM2025 (15) (1).xlsb", sheet_name="S.P.HC-2025", engine="pyxlsb")

In [128]:
planta2[['FECHA DE PRODUCCIÓN', 'TURNO', 'LOTE DE PRODUCCIÓN',
       'SECUENCIA DE PALLETS', 'NÚMERO DE TOLVADA', 'T. SECADO', 'SACOS',
       'PRESENT KG', 'CRITERIO', 'HUMEDAD', 'PROTEINA', 'FFA',
       'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'TVN', 'SOLUBLE', 'TONO', 'AOX',
       'ACIDO', 'NITRITOS', 'SALMONELLA', 'ENSAYO', 'ASTAXANTINA']]


planta2['FECHA DE PRODUCCIÓN'] = pd.to_numeric(planta2['FECHA DE PRODUCCIÓN'], errors='coerce')
planta2 = planta2[planta2["FECHA DE PRODUCCIÓN"].notna()]

cls_num_plant2 = [
       'SACOS',
       'PRESENT KG', 'HUMEDAD', 'PROTEINA', 'FFA',
       'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'TVN',  'TONO', 'AOX',
       'ACIDO', 'NITRITOS', 'SALMONELLA',
]
for cl in cls_num_plant2:
       planta2[cl] = pd.to_numeric(planta2[cl], errors='coerce')

In [129]:
planta2[['FECHA DE PRODUCCIÓN', 'TURNO', 'LOTE DE PRODUCCIÓN',
       'SECUENCIA DE PALLETS', 'NÚMERO DE TOLVADA', 'T. SECADO', 'SACOS',
       'PRESENT KG', 'CRITERIO', 'HUMEDAD', 'PROTEINA', 'FFA',
       'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'TVN', 'SOLUBLE', 'TONO', 'AOX',
       'ACIDO', 'NITRITOS', 'SALMONELLA', 'ENSAYO', 'ASTAXANTINA']]

,FECHA DE PRODUCCIÓN,TURNO,LOTE DE PRODUCCIÓN,SECUENCIA DE PALLETS,NÚMERO DE TOLVADA,T. SECADO,SACOS,PRESENT KG,CRITERIO,HUMEDAD,...,TEMP.ºC,TVN,SOLUBLE,TONO,AOX,ACIDO,NITRITOS,SALMONELLA,ENSAYO,ASTAXANTINA
0,45614.0,NaN,07-323-2024,3 AL 5,1.0,RD/FD,70.0,25.0,PARA MEZCLA,6.68,...,39.8,NaN,SI,3.0,3.040000,1.36,22.08,NaN,NaN,NaN
1,45614.0,NaN,07-323-2024,6 AL 7 + 34 SACOS,1.0,RD/FD,174.0,25.0,PARA MEZCLA,6.88,...,40.0,NaN,SI,3.5,2.940000,1.60,20.46,NaN,NaN,NaN
2,45635.0,NaN,07-344-2024,1 AL 3,1.0,RD/FD,210.0,25.0,PARA MEZCLA,5.62,...,39.9,NaN,SI,4.0,3.390000,1.43,20.46,NaN,NaN,NaN
3,45635.0,NaN,07-344-2024,4 AL 6,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.90,...,40.2,NaN,SI,4.0,2.720000,2.48,20.46,NaN,NaN,NaN
4,45635.0,NaN,07-344-2024,7 AL 9,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.46,...,41.0,NaN,SI,4.0,2.840000,1.46,20.46,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,45922.0,1.0,07-265-2025,29--30--31--+64 sacos,9.0,SD/FD,274.0,25.0,NaN,8.78,...,41.2,NaN,SI,4.0,4.500000,1.98,NaN,NaN,NaN,NaN
630,45923.0,1.0,07-266-2025,1--2,1.0,SD/FD,140.0,25.0,NaN,8.88,...,40.4,NaN,SI,4.5,4.185714,1.23,NaN,NaN,NaN,NaN
631,45923.0,1.0,07-266-2025,3--4--5,2.0,SD/FD,210.0,25.0,NaN,8.55,...,41.0,NaN,SI,4.5,4.133333,1.25,NaN,NaN,NaN,NaN
632,45923.0,1.0,07-266-2025,6--7--8,3.0,SD/FD,210.0,25.0,NaN,9.18,...,41.9,NaN,SI,4.5,4.133333,1.25,NaN,NaN,NaN,NaN
633,45923.0,1.0,07-266-2025,9--10--11--12--44 SACOS,4.0,SD/FD,324.0,25.0,NaN,9.22,...,41.4,NaN,SI,4.5,4.660494,1.65,NaN,NaN,NaN,NaN

In [130]:
planta_tolva_criterio = planta2.groupby(["T. SECADO", "CRITERIO"]).agg(tono=("TONO","median")).reset_index()
planta_tolva_criterio

   T. SECADO                                     CRITERIO  tono
0      RD/FD                             DESPACHO DIRECTO   4.0
1      RD/FD                            MEZCLA POR CENIZA   4.0
2      RD/FD                           MEZCLA POR NITRITO   4.0
3      RD/FD                  MEZCLA POR NITRITO Y CENIZA   4.0
4      RD/FD                          MEZCLA POR NITRITOS   4.0
5      RD/FD                 MEZCLA POR NITRITOS Y CENIZA   4.0
6      RD/FD               MEZCLA POR NITRITOS Y PROTEINA   4.0
7      RD/FD              MEZCLA POR NITRITOS Y PROTEINA    4.0
8      RD/FD              MEZCLA POR NITRITOS Y TONALIDAD   4.5
9      RD/FD       MEZCLA POR NITRITOS, PROTEINA Y CENIZA   4.0
10     RD/FD                          MEZCLA POR PROTEINA   4.0
11     RD/FD                 MEZCLA POR PROTEINA Y CENIZA   4.0
12     RD/FD      MEZCLA POR PROTEINA, CENIZA Y TONALIDAD   4.5
13     RD/FD                         MEZCLA POR TONALIDAD   4.5
14     RD/FD                              MEZCLA POR TONO   4.5
15     RD/FD                    MEZCLA POR TONO Y NITRITO   4.5
16     RD/FD                   MEZCLA POR TONO Y PROTEINA   4.5
17     RD/FD          MEZCLA POR TONO, NITRITO Y PROTEINA   4.5
18     RD/FD  MEZCLA POR TONO, NITRITO, CENIZA Y PROTEINA   4.5
19     RD/FD                    MEZCLA POR TONO, NITRITOS   4.5
20     RD/FD         MEZCLA POR TONO, NITRITOS Y PROTEINA   4.5
21     RD/FD                                  PARA MEZCLA   4.0
22        SD                             DESPACHO DIRECTO   4.0
23        SD                MEZCLA POR CENIZA Y TONALIDAD   4.5
24        SD                 MEZCLA POR PROTEINA Y CENIZA   4.5
25        SD              MEZCLA POR PROTEINA Y TONALIDAD   4.5
26        SD      MEZCLA POR PROTEINA, CENIZA Y TONALIDAD   4.5
27        SD                         MEZCLA POR TONALIDAD   4.5
28        SD                MEZCLA POR TONALIDAD Y CENIZA   4.5
29        SD              MEZCLA POR TONALIDAD Y PROTEINA   4.5
30        SD                                  PARA MEZCLA   3.5
31     SD/FD                             DESPACHO DIRECTO   4.5
32     SD/FD                        MEZCLA POR  TONALIDAD   4.5
33     SD/FD                            MEZCLA POR CENIZA   4.5
34     SD/FD                MEZCLA POR CENIZA Y TONALIDAD   4.5
35     SD/FD                          MEZCLA POR NITRITOS   4.5
36     SD/FD                 MEZCLA POR PROTEINA Y CENIZA   4.5
37     SD/FD      MEZCLA POR PROTEINA, CENIZA Y TONALIDAD   4.5
38     SD/FD                         MEZCLA POR TONALIDAD   4.5
39     SD/FD                MEZCLA POR TONALIDAD Y CENIZA   4.5
40     SD/FD              MEZCLA POR TONALIDAD Y PROTEINA   4.5
41     SD/FD                                  PARA MEZCLA   4.0
42     SD/FD                          REPROCESO TONALIDAD   5.0

In [131]:
plot_heatmap(
    df=planta_tolva_criterio,
    x_col="T. SECADO",
    y_col="CRITERIO",
    value_col="tono",
    width=1000,
    height=1000,
    
)

In [133]:
planta2["color_cat"] = 'col' + '-'+ planta2["TONO"].astype(str)
bins = [-np.inf, 3, 4.5, np.inf]
labels = ['bueno', 'medio', 'malo']
planta2['group_color'] = pd.cut(planta2['TONO'], bins=bins, labels=labels)

planta2["tolva"] = 'tolva' + '-'+planta2['NÚMERO DE TOLVADA'].astype(int).astype(str)

In [134]:
for cl in cls_num_plant2:
    f = plot_statistical_strip(
            df=planta2,
            x_col="color_cat",
            y_col=cl,
            title=f"<b>color vs {cl.replace('_', ' ').lower()} </b>",
            x_title="Color Agrupado", 
            
            )
    f.show()
    name = f"pl2_boxplot_color_{cl}.html"
    print(name)
    s3.save_plotly_html(f, name)

pl2_boxplot_color_SACOS.html

pl2_boxplot_color_PRESENT KG.html

pl2_boxplot_color_HUMEDAD.html

pl2_boxplot_color_PROTEINA.html

pl2_boxplot_color_FFA.html

pl2_boxplot_color_GRANUL MALLA 40.html

pl2_boxplot_color_CENIZA.html

pl2_boxplot_color_TEMP.ºC.html

pl2_boxplot_color_TVN.html

pl2_boxplot_color_TONO.html

pl2_boxplot_color_AOX.html

pl2_boxplot_color_ACIDO.html

pl2_boxplot_color_NITRITOS.html

pl2_boxplot_color_SALMONELLA.html

In [135]:
for cl in cls_num_plant2:
    f = plot_statistical_strip(
            df=planta2,
            x_col="group_color",
            y_col=cl,
            title=f"<b> color vs {cl.replace('_', ' ').lower()} </b>",
            x_title="Color Agrupado", 
            
            )
    f.show()
    name = f"pl2_boxplot_grupo_color_{cl}.html"
    print(name)
    s3.save_plotly_html(f, name)

pl2_boxplot_grupo_color_SACOS.html

pl2_boxplot_grupo_color_PRESENT KG.html

pl2_boxplot_grupo_color_HUMEDAD.html

pl2_boxplot_grupo_color_PROTEINA.html

pl2_boxplot_grupo_color_FFA.html

pl2_boxplot_grupo_color_GRANUL MALLA 40.html

pl2_boxplot_grupo_color_CENIZA.html

pl2_boxplot_grupo_color_TEMP.ºC.html

pl2_boxplot_grupo_color_TVN.html

pl2_boxplot_grupo_color_TONO.html

pl2_boxplot_grupo_color_AOX.html

pl2_boxplot_grupo_color_ACIDO.html

pl2_boxplot_grupo_color_NITRITOS.html

pl2_boxplot_grupo_color_SALMONELLA.html

In [147]:
planta2[[
       'SACOS',
       'PRESENT KG', 'CRITERIO', 'HUMEDAD', 'PROTEINA', 'FFA',
       'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'TVN', 'SOLUBLE', 'TONO', 'AOX',
       'ACIDO', 'NITRITOS', 'SALMONELLA'

]]

,SACOS,PRESENT KG,CRITERIO,HUMEDAD,PROTEINA,FFA,GRANUL MALLA 40,CENIZA,TEMP.ºC,TVN,SOLUBLE,TONO,AOX,ACIDO,NITRITOS,SALMONELLA
0,70.0,25.0,PARA MEZCLA,6.68,48.28,NaN,35.50,24.22,39.8,NaN,SI,3.0,3.040000,1.36,22.08,NaN
1,174.0,25.0,PARA MEZCLA,6.88,51.11,NaN,36.00,21.68,40.0,NaN,SI,3.5,2.940000,1.60,20.46,NaN
2,210.0,25.0,PARA MEZCLA,5.62,54.06,NaN,34.75,23.12,39.9,NaN,SI,4.0,3.390000,1.43,20.46,NaN
3,210.0,25.0,PARA MEZCLA,6.90,52.35,NaN,35.25,23.12,40.2,NaN,SI,4.0,2.720000,2.48,20.46,NaN
4,210.0,25.0,PARA MEZCLA,6.46,51.97,NaN,38.30,23.12,41.0,NaN,SI,4.0,2.840000,1.46,20.46,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,274.0,25.0,NaN,8.78,51.68,NaN,39.85,21.40,41.2,NaN,SI,4.0,4.500000,1.98,NaN,NaN
630,140.0,25.0,NaN,8.88,NaN,NaN,40.25,NaN,40.4,NaN,SI,4.5,4.185714,1.23,NaN,NaN
631,210.0,25.0,NaN,8.55,NaN,NaN,40.38,NaN,41.0,NaN,SI,4.5,4.133333,1.25,NaN,NaN
632,210.0,25.0,NaN,9.18,NaN,NaN,41.25,NaN,41.9,NaN,SI,4.5,4.133333,1.25,NaN,NaN
633,324.0,25.0,NaN,9.22,NaN,NaN,39.89,NaN,41.4,NaN,SI,4.5,4.660494,1.65,NaN,NaN

In [148]:
variables = ['PROTEINA', 'HUMEDAD', 'TONO', 'GRANUL MALLA 40', 'CENIZA', 'TEMP.ºC', 'ACIDO']
df_final2 = procesar_clustering(planta2, variables, n_clusters=3, pesos_personalizados=None)

df_final2

,FECHA DE PRODUCCIÓN,TURNO,LOTE DE PRODUCCIÓN,SECUENCIA DE PALLETS,NÚMERO DE TOLVADA,T. SECADO,SACOS,PRESENT KG,CRITERIO,HUMEDAD,...,Cluster_Label,PC1,PC2,Media_PROTEINA,Media_HUMEDAD,Media_TONO,Media_GRANUL MALLA 40,Media_CENIZA,Media_TEMP.ºC,Media_ACIDO
0,45614.0,NaN,07-323-2024,3 AL 5,1.0,RD/FD,70.0,25.0,PARA MEZCLA,6.68,...,Grupo 0,-3.031850,-0.453870,49.844247,7.646471,4.158824,35.226647,23.322176,40.797588,1.651814
1,45614.0,NaN,07-323-2024,6 AL 7 + 34 SACOS,1.0,RD/FD,174.0,25.0,PARA MEZCLA,6.88,...,Grupo 1,0.408206,-0.040894,51.671534,7.423578,4.107759,30.220970,21.957866,41.232759,1.422904
2,45635.0,NaN,07-344-2024,1 AL 3,1.0,RD/FD,210.0,25.0,PARA MEZCLA,5.62,...,Grupo 1,1.361076,-2.282246,51.671534,7.423578,4.107759,30.220970,21.957866,41.232759,1.422904
3,45635.0,NaN,07-344-2024,4 AL 6,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.90,...,Grupo 1,0.015345,-1.180156,51.671534,7.423578,4.107759,30.220970,21.957866,41.232759,1.422904
4,45635.0,NaN,07-344-2024,7 AL 9,1.0,RD/FD,210.0,25.0,PARA MEZCLA,6.46,...,Grupo 1,0.043964,-1.241460,51.671534,7.423578,4.107759,30.220970,21.957866,41.232759,1.422904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,45922.0,1.0,07-265-2025,29--30--31--+64 sacos,9.0,SD/FD,274.0,25.0,NaN,8.78,...,Grupo 2,0.783237,1.527471,51.097855,8.441164,4.038793,39.339095,21.838180,40.825431,1.446069
630,45923.0,1.0,07-266-2025,1--2,1.0,SD/FD,140.0,25.0,NaN,8.88,...,Grupo 2,-0.185237,1.354120,51.097855,8.441164,4.038793,39.339095,21.838180,40.825431,1.446069
631,45923.0,1.0,07-266-2025,3--4--5,2.0,SD/FD,210.0,25.0,NaN,8.55,...,Grupo 2,-0.080945,0.941520,51.097855,8.441164,4.038793,39.339095,21.838180,40.825431,1.446069
632,45923.0,1.0,07-266-2025,6--7--8,3.0,SD/FD,210.0,25.0,NaN,9.18,...,Grupo 2,-0.005038,1.465928,51.097855,8.441164,4.038793,39.339095,21.838180,40.825431,1.446069
633,45923.0,1.0,07-266-2025,9--10--11--12--44 SACOS,4.0,SD/FD,324.0,25.0,NaN,9.22,...,Grupo 2,-0.126392,1.388243,51.097855,8.441164,4.038793,39.339095,21.838180,40.825431,1.446069

In [151]:
cls_group = ["Cluster_Label",  "Media_TONO", "Media_PROTEINA", "Media_HUMEDAD", "Media_TEMP.ºC", "Media_GRANUL MALLA 40", "Media_CENIZA", "Media_ACIDO"]
plant2_summary = df_final2[cls_group].drop_duplicates().round(2).sort_values('Cluster_Label')
s3.save_dataframe(plant2_summary, "plant2_summary_group.csv")
plant2_summary

,Cluster_Label,Media_TONO,Media_PROTEINA,Media_HUMEDAD,Media_TEMP.ºC,Media_GRANUL MALLA 40,Media_CENIZA,Media_ACIDO
0,Grupo 0,4.16,49.84,7.65,40.80,35.23,23.32,1.65
1,Grupo 1,4.11,51.67,7.42,41.23,30.22,21.96,1.42
11,Grupo 2,4.04,51.10,8.44,40.83,39.34,21.84,1.45

In [152]:
f = plot_scatter(
df=df_final2,
x_col='PC1',
y_col='PC2', 
group_col='Cluster_Label',
hover_data_cols=["LOTE DE PRODUCCIÓN",  "Media_TONO", "Media_PROTEINA", "Media_HUMEDAD", "Media_TEMP.ºC", "Media_GRANUL MALLA 40", "Media_CENIZA"],
title='<b>Mapa de Clusters (PCA)</b><br><i>Agrupación por similitud de proceso Planta 2</i>'
)
f.show()
s3.save_plotly_html(f, "componentes_planta2.html")

In [154]:
for cl in cls_num_plant2+["TONO"]:
    f = plot_statistical_strip(
            df=df_final2,
            x_col="Cluster_Label",
            y_col=cl,
            title=f"<b> color vs {cl.replace('_', ' ').lower()} </b>",
            x_title="Color Agrupado", 
            
            )
    f.show()
    name = f"pl2_boxplot_grupo_color_{cl}.html"
    print(name)
    s3.save_plotly_html(f, name)

pl2_boxplot_grupo_color_SACOS.html

pl2_boxplot_grupo_color_PRESENT KG.html

pl2_boxplot_grupo_color_HUMEDAD.html

pl2_boxplot_grupo_color_PROTEINA.html

pl2_boxplot_grupo_color_FFA.html

pl2_boxplot_grupo_color_GRANUL MALLA 40.html

pl2_boxplot_grupo_color_CENIZA.html

pl2_boxplot_grupo_color_TEMP.ºC.html

pl2_boxplot_grupo_color_TVN.html

pl2_boxplot_grupo_color_TONO.html

pl2_boxplot_grupo_color_AOX.html

pl2_boxplot_grupo_color_ACIDO.html

pl2_boxplot_grupo_color_NITRITOS.html

pl2_boxplot_grupo_color_SALMONELLA.html

pl2_boxplot_grupo_color_TONO.html